server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/harudb?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 123qwe
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  mustache:
    suffix: .html

front:
  base_url: http://localhost:3000/